// Code generated by MockGen. DO NOT EDIT.
// Source: dependencies.go
//
// Generated by this command:
//
//	mockgen -source=dependencies.go -destination=mock/mock_dependencies.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entities "github.com/Laaaaksh/gohighlevel-round1/internal/modules/post/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockPostReader is a mock of PostReader interface.
type MockPostReader struct {
	ctrl     *gomock.Controller
	recorder *MockPostReaderMockRecorder
	isgomock struct{}
}

// MockPostReaderMockRecorder is the mock recorder for MockPostReader.
type MockPostReaderMockRecorder struct {
	mock *MockPostReader
}

// NewMockPostReader creates a new mock instance.
func NewMockPostReader(ctrl *gomock.Controller) *MockPostReader {
	mock := &MockPostReader{ctrl: ctrl}
	mock.recorder = &MockPostReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostReader) EXPECT() *MockPostReaderMockRecorder {
	return m.recorder
}

// ListByAuthors mocks base method.
func (m *MockPostReader) ListByAuthors(ctx context.Context, authorIDs []string, cursor string, limit int) ([]entities.PostResponse, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAuthors", ctx, authorIDs, cursor, limit)
	ret0, _ := ret[0].([]entities.PostResponse)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByAuthors indicates an expected call of ListByAuthors.
func (mr *MockPostReaderMockRecorder) ListByAuthors(ctx, authorIDs, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAuthors", reflect.TypeOf((*MockPostReader)(nil).ListByAuthors), ctx, authorIDs, cursor, limit)
}

// MockFollowReader is a mock of FollowReader interface.
type MockFollowReader struct {
	ctrl     *gomock.Controller
	recorder *MockFollowReaderMockRecorder
	isgomock struct{}
}

// MockFollowReaderMockRecorder is the mock recorder for MockFollowReader.
type MockFollowReaderMockRecorder struct {
	mock *MockFollowReader
}

// NewMockFollowReader creates a new mock instance.
func NewMockFollowReader(ctrl *gomock.Controller) *MockFollowReader {
	mock := &MockFollowReader{ctrl: ctrl}
	mock.recorder = &MockFollowReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowReader) EXPECT() *MockFollowReaderMockRecorder {
	return m.recorder
}

// ListFollowees mocks base method.
func (m *MockFollowReader) ListFollowees(ctx context.Context, followerID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowees", ctx, followerID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowees indicates an expected call of ListFollowees.
func (mr *MockFollowReaderMockRecorder) ListFollowees(ctx, followerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowees", reflect.TypeOf((*MockFollowReader)(nil).ListFollowees), ctx, followerID)
}
