// Code generated by MockGen. DO NOT EDIT.
// Source: core.go
//
// Generated by this command:
//
//	mockgen -source=core.go -destination=mock/mock_core.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entities "github.com/Laaaaksh/gohighlevel-round1/internal/modules/post/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUserChecker is a mock of UserChecker interface.
type MockUserChecker struct {
	ctrl     *gomock.Controller
	recorder *MockUserCheckerMockRecorder
	isgomock struct{}
}

// MockUserCheckerMockRecorder is the mock recorder for MockUserChecker.
type MockUserCheckerMockRecorder struct {
	mock *MockUserChecker
}

// NewMockUserChecker creates a new mock instance.
func NewMockUserChecker(ctrl *gomock.Controller) *MockUserChecker {
	mock := &MockUserChecker{ctrl: ctrl}
	mock.recorder = &MockUserCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserChecker) EXPECT() *MockUserCheckerMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockUserChecker) Exists(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserCheckerMockRecorder) Exists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserChecker)(nil).Exists), ctx, userID)
}

// MockICore is a mock of ICore interface.
type MockICore struct {
	ctrl     *gomock.Controller
	recorder *MockICoreMockRecorder
	isgomock struct{}
}

// MockICoreMockRecorder is the mock recorder for MockICore.
type MockICoreMockRecorder struct {
	mock *MockICore
}

// NewMockICore creates a new mock instance.
func NewMockICore(ctrl *gomock.Controller) *MockICore {
	mock := &MockICore{ctrl: ctrl}
	mock.recorder = &MockICoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICore) EXPECT() *MockICoreMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockICore) CreatePost(ctx context.Context, req entities.CreatePostRequest) (*entities.CreatePostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, req)
	ret0, _ := ret[0].(*entities.CreatePostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockICoreMockRecorder) CreatePost(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockICore)(nil).CreatePost), ctx, req)
}

// ListByUser mocks base method.
func (m *MockICore) ListByUser(ctx context.Context, userID, cursor string, limit int) ([]entities.PostResponse, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, cursor, limit)
	ret0, _ := ret[0].([]entities.PostResponse)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockICoreMockRecorder) ListByUser(ctx, userID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockICore)(nil).ListByUser), ctx, userID, cursor, limit)
}
