// Code generated by MockGen. DO NOT EDIT.
// Source: core.go
//
// Generated by this command:
//
//	mockgen -source=core.go -destination=mock/mock_core.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserChecker is a mock of UserChecker interface.
type MockUserChecker struct {
	ctrl     *gomock.Controller
	recorder *MockUserCheckerMockRecorder
	isgomock struct{}
}

// MockUserCheckerMockRecorder is the mock recorder for MockUserChecker.
type MockUserCheckerMockRecorder struct {
	mock *MockUserChecker
}

// NewMockUserChecker creates a new mock instance.
func NewMockUserChecker(ctrl *gomock.Controller) *MockUserChecker {
	mock := &MockUserChecker{ctrl: ctrl}
	mock.recorder = &MockUserCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserChecker) EXPECT() *MockUserCheckerMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockUserChecker) Exists(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserCheckerMockRecorder) Exists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserChecker)(nil).Exists), ctx, userID)
}

// MockICore is a mock of ICore interface.
type MockICore struct {
	ctrl     *gomock.Controller
	recorder *MockICoreMockRecorder
	isgomock struct{}
}

// MockICoreMockRecorder is the mock recorder for MockICore.
type MockICoreMockRecorder struct {
	mock *MockICore
}

// NewMockICore creates a new mock instance.
func NewMockICore(ctrl *gomock.Controller) *MockICore {
	mock := &MockICore{ctrl: ctrl}
	mock.recorder = &MockICoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICore) EXPECT() *MockICoreMockRecorder {
	return m.recorder
}

// Follow mocks base method.
func (m *MockICore) Follow(ctx context.Context, followerID, followeeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, followerID, followeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockICoreMockRecorder) Follow(ctx, followerID, followeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockICore)(nil).Follow), ctx, followerID, followeeID)
}

// ListFollowees mocks base method.
func (m *MockICore) ListFollowees(ctx context.Context, followerID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowees", ctx, followerID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowees indicates an expected call of ListFollowees.
func (mr *MockICoreMockRecorder) ListFollowees(ctx, followerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowees", reflect.TypeOf((*MockICore)(nil).ListFollowees), ctx, followerID)
}
